---
name: CI
# yamllint disable-line rule:truthy
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - denverton
          # - geminilake
    name: build ${{ matrix.arch }} kernel modules
    steps:
      - name: Clone Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Kernel configure and build
        uses: chickenandpork/synology-docker-kernel-action@ba1dcc2fcbcafd66ec2344d09ebbef5a20bfb713
        id: build
        with:
          artifacts: net/ipv4/netfilter/ipt_REJECT.ko net/ipv4/netfilter/nf_reject_ipv4.ko net/netfilter/xt_comment.ko
          dsm-version: '7.2'
          module-deactivate: CONFIG_NFSD CONFIG_NFS_FS
          module-modularize: CONFIG_IP_NF_TARGET_REJECT CONFIG_NETFILTER_XT_MATCH_COMMENT
          package-arch: ${{ matrix.arch }}
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          path: ${{ github.workspace }}/${{ steps.build.outputs.archive }}
          retention-days: 7
      - name: Debug Info
        run: |
          ls -al .
